### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by userlandkernel** [googleprojectzero/ktrw#2] opened 2019-11-26 10:53 UTC
When building ktrw_gdb_stub I get the following warning (treated as error):
```
error: using extended field designator is an extension [-Werror,-Wextended-offsetof]
```

I solved it by adding the following CFLAGS in the Makefile:
-Wno-unknown-warning-option -Wno-invalid-offsetof -Wno-extended-offsetof

**Comment by bazad** [comment] 2019-11-26 16:56
Interesting, I don’t see any build errors on my system; what macOS version and clang version are you using?

**Comment by bazad** [comment] 2019-12-21 22:01
Closing since I can’t reproduce the issue.

**Closed by bazad** 2019-12-21 22:01 UTC
